version: "3.5"

services:
  planty_nginx:
    image: ${GHCR_IMAGE}
    container_name: planty_nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - proxynet

networks:
  proxynet:
    name: plantynet
